Added some DBD-SQLite vulnerabities
briandfoy/cpan-security-advisory pull request #20
Opened 2022-06-21 16:30 UTC by robrwo

These come from [1], going back to 2018. There are many before from before then

[1] https://www.cvedetails.com/vulnerability-list/vendor_id-9237/Sqlite.html

2022-06-21 22:36 UTC, briandfoy requested changes
Just fix up some yaml things and we are all set. I'm following yamllint's rules with everything.

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +- affected_versions: "<1.65_03"
Add a line for `---` above this one

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'In SQLite before 3.32.3, select.c mishandles query-flattener optimization, leading to a multiSelectOrderBy heap overflow because of misuse of transitive properties for constant propag
This is going to look like a lot of requests, but it's really just the same thing over and over. Since I think you're going to contribute a lot, I'll get you used to the things that can let me merge it right off.

Use the folded style here so yamllint doesn't complain about long lines:

    description: >
      In SQLite ...

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: ext/fts3/fts3_snippet.c in SQLite before 3.32.0 has a NULL pointer dereference via a crafted matchinfo() query.
Folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'SQLite before 3.32.0 allows a virtual table to be renamed to the name of one of its shadow tables, related to alter.c and build.c.'
Folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'ext/fts3/fts3.c in SQLite before 3.32.0 has a use-after-free in fts3EvalNextRow, related to the snippet feature.'
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: SQLite through 3.32.0 has a segmentation fault in sqlite3ExprCodeTarget in expr.c.
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'In SQLite through 3.31.1, the ALTER TABLE implementation has a use-after-free, as demonstrated by an ORDER BY clause that belongs to a compound SELECT statement.'
Folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: Buffer overflow in the skip-scan optimization in SQLite 3.8.2 allows remote attackers to cause a denial of service (crash) via crafted SQL statements.
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'SQLite before 3.8.9 does not properly implement the dequoting of collation-sequence names, which allows context-dependent attackers to cause a denial of service (uninitialized memory
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'The sqlite3VdbeExec function in vdbe.c in SQLite before 3.8.9 does not properly implement comparison operators, which allows context-dependent attackers to cause a denial of service (
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'The sqlite3VXPrintf function in printf.c in SQLite before 3.8.9 does not properly handle precision and width values during floating-point conversions, which allows context-dependent a
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'The getNodeSize function in ext/rtree/rtree.c in SQLite through 3.19.3, as used in GDAL and other products, mishandles undersized RTree blobs in a crafted database, leading to a heap-
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'SQLite 3.25.2, when queries are run on a table with a malformed PRIMARY KEY, allows remote attackers to cause a denial of service (application crash) by leveraging the ability to run
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'SQLite 3.30.1 mishandles certain parser-tree rewriting, related to expr.c, vdbeaux.c, and window.c. This is caused by incorrect sqlite3WindowRewrite() error handling.'
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'multiSelect in select.c in SQLite 3.30.1 mishandles certain errors during parsing, as demonstrated by errors from sqlite3WindowRewrite() calls. NOTE: this vulnerability exists because
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: "ext/misc/zipfile.c in SQLite 3.30.1 mishandles certain uses of INSERT INTO in situations involving embedded '\\0' characters in filenames, leading to a memory-management error that ca
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: selectExpander in select.c in SQLite 3.30.1 proceeds with WITH stack unwinding even after a parsing error.
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'In SQLite 3.31.1, isAuxiliaryVtabOperator allows attackers to trigger a NULL pointer dereference and segmentation fault because of generated column optimizations.'
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: SQLite through 3.31.1 allows attackers to cause a denial of service (segmentation fault) via a malformed window-function query because the AggInfo object's initialization is mishandled
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: SQLite through 3.32.0 has an integer overflow in sqlite3_str_vappendf in printf.c.
folded style

2022-06-21 22:36 UTC, briandfoy commented on cpansa/CPANSA-DBD-SQLite.yml
> +  severity: medium
If you like, you can add a `reviewed_by` key as seen in CONTRIBUTING.md.

2022-06-22 11:44 UTC, robrwo commented on cpansa/CPANSA-DBD-SQLite.yml
> +  description: 'In SQLite before 3.32.3, select.c mishandles query-flattener optimization, leading to a multiSelectOrderBy heap overflow because of misuse of transitive properties for constant propag
Maybe you can modify `util_make_record` to do this automatically

2022-06-22 12:39 UTC, merged